

```
# 1. Develop a python program to utilize NumPy and perform the following operations
a. Read and Print 1D array
b. Read two 1D array and display the common numbers present in both the
arrays.
c. Read 1D array with 12 elements and convert it into 2D array of size (2, 6) and
(3, 4).
d. Read 1D array with 12 elements and convert it into 3D array.
e. Split the 1D array into 2, 3 and 4 arrays.
f. Demonstrate the concatenation of two 1D array.
g. Sort the 1D array in ascending and descending order.
h. Display all the even numbers of 1D array.
```



**Read and Print 1D array**

In [5]:
import numpy as np
arr = np.array(input("Enter the elements of the array (space-separated): ").split(), dtype=int)
print("1D Array:", arr)
print(type(arr))


Enter the elements of the array (space-separated): 2 5 6 5
1D Array: [2 5 6 5]
<class 'numpy.ndarray'>



**Read two 1D array and display the common numbers present in both the
arrays.**


In [6]:
import numpy as np
def read_1d_array():
    arr = np.array(input("Enter the elements of the array (space-separated): ").split(), dtype=int)
    return arr
def find_common_numbers(arr1, arr2):
    common = np.intersect1d(arr1, arr2)
    return common

arr1 = read_1d_array()
arr2 = read_1d_array()

# Find and display the common numbers
common_numbers = find_common_numbers(arr1, arr2)
print("Common Numbers:", common_numbers)



Enter the elements of the array (space-separated): 1 2 3 4 5 6
Enter the elements of the array (space-separated): 5 6 7 8 9
Common Numbers: [5 6]


The np.intersect1d() function from NumPy is used to find the common numbers between two 1D arrays. It takes the two arrays as input and returns a new array containing the common elements.

**Read 1D array with 12 elements and convert it into 2D array of size (2, 6) and
(3, 4)**

In [7]:
import numpy as np

def read_1d_array():
    arr = np.array(input("Enter 12 elements of the array (space-separated): ").split(), dtype=int)
    return arr

def convert_to_2d(arr):
    arr_2d_1 = arr.reshape(2, 6)
    arr_2d_2 = arr.reshape(3, 4)
    return arr_2d_1, arr_2d_2

arr = read_1d_array()

# Convert the array to 2D arrays
arr_2d_1, arr_2d_2 = convert_to_2d(arr)

# Display the 2D arrays
print("2D Array (2, 6):")
print(arr_2d_1)
print("2D Array (3, 4):")
print(arr_2d_2)


Enter 12 elements of the array (space-separated): 1 2 3 4 5 6 7 8 9 10 11 12
2D Array (2, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2D Array (3, 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**Read 1D array with 12 elements and convert it into 3D array.**

In [11]:
import numpy as np

def read_1d_array():
    arr = np.array(input("Enter the elements of the array (space-separated): ").split(), dtype=int)
    return arr

def convert_to_3d(arr):
    arr_3d = arr.reshape(2,3,2)
    return arr_3d

arr = read_1d_array()
arr_3d = convert_to_3d(arr)

print("3D Array:")
print(arr_3d)


Enter the elements of the array (space-separated): 1 2 3 4 5 6 7 8 9 10 11 12
3D Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [18]:
import numpy as np

def read_1d_array():
    arr = np.array(input("Enter the elements of the array (space-separated): ").split(), dtype=int)
    return arr

def split_array(arr,n):
    split_arr = np.split(arr, n)
    return split_arr

# Read the 1D array with 12 elements
arr = read_1d_array()


arr_2 = split_array(arr, 2)
arr_3 = split_array(arr, 3)
arr_4 = split_array(arr, 4)

# Display the 2D array

print(arr_2)
print()
print(arr_3)
print()
print(arr_4)


Enter the elements of the array (space-separated): 1 2 3 4 5 6 7 8 9 1 0 2
[array([1, 2, 3, 4, 5, 6]), array([7, 8, 9, 1, 0, 2])]

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([9, 1, 0, 2])]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([1, 0, 2])]


**Demonstrate the concatenation of two 1D array**

In [21]:
import numpy as np

def read_1d_array():
    arr = np.array(input("Enter the elements of the array (space-separated): ").split(), dtype=int)
    return arr

def concatenate_arrays(arr1, arr2):
    concatenated = np.concatenate((arr1, arr2))
    return concatenated

arr1 = read_1d_array()

arr2 = read_1d_array()

concatenated_array = concatenate_arrays(arr1, arr2)

print("Concatenated Array:")
print(concatenated_array)


Enter the elements of the array (space-separated): 1 2 3
Enter the elements of the array (space-separated): 4 5 6
Concatenated Array:
[1 2 3 4 5 6]


**Sort the 1D array in ascending and descending order.**

In [23]:
import numpy as np

def read_1d_array():
    arr = np.array(input("Enter the elements of the array (space-separated): ").split(), dtype=int)
    return arr

def sort_array(arr):
    sorted_asc = np.sort(arr)
    sorted_desc = np.sort(arr)[::-1]
    return sorted_asc, sorted_desc

arr = read_1d_array()

sorted_asc, sorted_desc = sort_array(arr)

print("Sorted Array (Ascending Order):")
print(sorted_asc)
print("Sorted Array (Descending Order):")
print(sorted_desc)


Enter the elements of the array (space-separated): 1 8 5 6 7 9 55 44 6 66
Sorted Array (Ascending Order):
[ 1  5  6  6  7  8  9 44 55 66]
Sorted Array (Descending Order):
[66 55 44  9  8  7  6  6  5  1]


**Display all the even numbers of 1D arra**

In [22]:
import numpy as np

def read_1d_array():
    arr = np.array(input("Enter the elements of the array (space-separated): ").split(), dtype=int)
    return arr

def get_even_numbers(arr):
    even_nums = arr[arr % 2 == 0]
    return even_nums

arr = read_1d_array()

even_numbers = get_even_numbers(arr)

print("Even Numbers:", even_numbers)


Enter the elements of the array (space-separated): 1 2 3 4 5 6 7 8 9
Even Numbers: [2 4 6 8]
